#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
from datetime import datetime, timezone
import html

BASE_OUTPUT = Path("/home/eva/openclaw_workspace/openclaw-knowledge-radio/output")
SITE_DIR = Path("/home/eva/openclaw_workspace/openclaw_podcast/openclaw-knowledge-radio/docs")
AUDIO_DIR = SITE_DIR / "audio"


def discover_episodes():
    episodes = []
    if not BASE_OUTPUT.exists():
        return episodes
    for d in sorted(BASE_OUTPUT.iterdir()):
        if not d.is_dir():
            continue
        date = d.name
        mp3 = d / f"podcast_{date}.mp3"
        script = d / f"podcast_script_{date}_llm_clean.txt"
        if not mp3.exists():
            continue
        episodes.append({
            "date": date,
            "title": f"Daily Podcast {date}",
            "mp3_src": mp3,
            "mp3_name": mp3.name,
            "script": script if script.exists() else None,
            "script_name": script.name if script.exists() else None,
        })
    episodes.sort(key=lambda x: x["date"], reverse=True)
    return episodes


def render_index(episodes):
    items = []
    for ep in episodes:
        s_link = f'<a href="{html.escape(ep["script_name"])}">script</a>' if ep["script_name"] else ""
        items.append(
            f"<li><strong>{ep['title']}</strong><br>"
            f"<audio controls src=\"audio/{html.escape(ep['mp3_name'])}\"></audio><br>"
            f"<a href=\"audio/{html.escape(ep['mp3_name'])}\">download mp3</a> {s_link}</li>"
        )
    body = "\n".join(items) if items else "<li>No episodes yet.</li>"
    return f"""<!doctype html>
<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>
<title>Daily Podcast</title></head>
<body>
<h1>Daily Podcast</h1>
<p>Auto-generated daily summaries.</p>
<ul>{body}</ul>
</body></html>
"""


def render_feed(episodes, site_url: str):
    now = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S GMT")
    items = []
    for ep in episodes[:60]:
        pub = datetime.strptime(ep["date"], "%Y-%m-%d").strftime("%a, %d %b %Y 08:00:00 GMT")
        mp3_url = f"{site_url}/audio/{ep['mp3_name']}"
        items.append(f"""
    <item>
      <title>{html.escape(ep['title'])}</title>
      <guid>{mp3_url}</guid>
      <pubDate>{pub}</pubDate>
      <enclosure url=\"{mp3_url}\" type=\"audio/mpeg\" />
      <description>Daily autogenerated science podcast.</description>
    </item>""")
    return f"""<?xml version='1.0' encoding='UTF-8'?>
<rss version='2.0'>
  <channel>
    <title>Daily Podcast</title>
    <link>{site_url}</link>
    <description>Daily autogenerated science podcast</description>
    <language>en</language>
    <lastBuildDate>{now}</lastBuildDate>
    {''.join(items)}
  </channel>
</rss>
"""


def main():
    site_url = "https://wenyuedai.github.io/openclaw_podcast"
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)

    episodes = discover_episodes()

    # copy media/script files
    for ep in episodes:
        (AUDIO_DIR / ep["mp3_name"]).write_bytes(ep["mp3_src"].read_bytes())
        if ep["script"]:
            (SITE_DIR / ep["script_name"]).write_text(ep["script"].read_text(encoding="utf-8"), encoding="utf-8")

    # remove stale files
    keep_audio = {ep["mp3_name"] for ep in episodes}
    for f in AUDIO_DIR.glob("*.mp3"):
        if f.name not in keep_audio:
            f.unlink()

    (SITE_DIR / "episodes.json").write_text(json.dumps([
        {"date": e["date"], "title": e["title"], "audio": f"audio/{e['mp3_name']}", "script": e["script_name"]}
        for e in episodes
    ], indent=2), encoding="utf-8")

    (SITE_DIR / "index.html").write_text(render_index(episodes), encoding="utf-8")
    (SITE_DIR / "feed.xml").write_text(render_feed(episodes, site_url), encoding="utf-8")
    print(f"Built site with {len(episodes)} episode(s): {SITE_DIR}")


if __name__ == "__main__":
    main()
